[package]
name = "pair-commit-rust"
version = "0.1.0"
description = ""
license = "MIT"
repository = "https://github.com/jjmark15/pair-commit-rust"

[[module]]
name = "pair-commit-tool"
source = "target/wasm32-wasi/release/pair-commit-tool.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "pair-commit-tool"
module = "pair-commit-tool"
